name: Test CI

on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-18.04
    env:
      PYTHON_DEPS: |
        python python-pip python-setuptools python-dev
        python-msgpack python-yaml python-argparse python-six python-gevent
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install test dependencies
        run: |
          sudo apt-get install ${PYTHON_DEPS}
          echo python --version
          pwd
          git describe

      - name: Build tarantool
        run: |
          pushd static-build
          cmake -DCMAKE_TARANTOOL_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo;-DENABLE_WERROR=ON" ..
          make -j
          popd

      - name: test-build
        run: |
          pushd test
          ./test-run.py --builddir ../static-build/tarantool-prefix/src/tarantool-build
          popd
