name: Test CI

on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-18.04
    env:
      PYTHON_DEPS: |
        python python-pip python-setuptools python-dev
        python-msgpack python-yaml python-argparse python-six python-gevent
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install test dependencies
        run: |
          sudo apt-get install ${PYTHON_DEPS}
          echo python --version
          pwd
          git describe

      - name: Cache build files
        uses: actions/cache@v2
        with:
          path: ./build
          key: tarantool-build-${{ runner.os }}
          restore-keys: tarantool-build-

      - name: Build tarantool
        run: |
          mkdir -p build
          pushd build
          cmake -DCMAKE_TARANTOOL_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo;-DENABLE_WERROR=ON" ..
          make -j
          popd

      - name: Test cache used properly
        run: tarantool -v

